### ISSUE TITLE
Error when running tests on windows machine

### ISSUE THREAD

**Issue by icereed** [DispatchMe/meteor-mocha-phantomjs#12]
Hi there,

when executing a test I hit following error:

![Screenshot](https://cloud.githubusercontent.com/assets/444269/14942396/0cfee182-0fbc-11e6-9f26-b2f224bf309a.PNG)

Is there a possibility to resolve that?

**Comment by icereed** [comment]
I just discovered, the same error occures when running `meteor test --once --driver-package dispatch:mocha`.

**Comment by aldeed** [comment]
Might be fixed by `dispatch:mocha-phantomjs@0.1.1`, not sure

**Comment by serut** [comment]
Issue with windows 10 too

**Comment by aldeed** [comment]
Can anyone verify that you can run tests on Windows using some other driver package? The most likely culprit is the phantomjs package since that is binary, but I want to narrow it down.

**Comment by AptusTim** [comment]
practicalmeteor:mocha had problems running tests on Windows 10.
They seem to have fixed it in practicalmeteor:mocha@=2.4.5-rc5.5
At this time, I can run tests with phantomjs on Windows 10.

**Comment by aldeed** [comment]
> At this time, I can run tests with phantomjs on Windows 10.

@AptusTim Using `dispatch:mocha-phantomjs` driver? Or using `practicalmeteor:mocha` + spacejam?

**Comment by AptusTim** [comment]
@aldeed using dispatch:mocha-phantomjs driver. Haven't tried spacejam yet.

**Comment by aldeed** [comment]
Closing since this repo is being replaced by the updated [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha). Please repost in that repo if this is still an issue.
