### ISSUE TITLE
*.app-test.* under imports not being run

### ISSUE THREAD

**Issue by hwillson** [DispatchMe/meteor-mocha-phantomjs#15]
Hi guys - it looks like \*.app-test.\* files under `imports` aren't run when using this driver in full app testing mode. I've created a quick repro showing the issue [here](https://github.com/hwillson/meteor-mocha-phantomjs-test). Is this expected behaviour? Thanks!

**Comment by thebarty** [comment]
plus 1 for this being fixed. just ran into the same issue

**Comment by ramijarrar** [comment]
It looks like the issue isn't specific to this test driver https://github.com/practicalmeteor/meteor-mocha/issues/41

**Comment by hwillson** [comment]
Thanks @ramijarrar - I just ran my test using the latest Meteor version in the `devel` branch, and this issue is now fixed.
