### ISSUE TITLE
server.js Error: Meteor code must always run within a Fiber

### ISSUE THREAD

**Issue by erabonza** [DispatchMe/meteor-mocha-phantomjs#17]
Hi our tests is passing using practicalmeteor:mocha, but trying to run them on our CI (jenkins) its failing with errors when it finishes running the tests:

METEOR@1.3.2.4

dispatch:mocha-core@0.0.2
dispatch:mocha-phantomjs@0.1.2
dispatch:phantomjs-tests@0.0.5
dispatch:run-as-user@1.1.1

 ```
=> Started your app.

=> App running at: http://localhost:3000/
I20160601-23:40:48.415(0)? 
I20160601-23:40:48.605(0)? 
I20160601-23:40:48.606(0)?   12 passing (5s)
I20160601-23:40:48.607(0)? 
I20160601-23:40:48.608(0)? 
I20160601-23:40:48.608(0)? --------------------------------
I20160601-23:40:48.609(0)? ----- RUNNING CLIENT TESTS -----
I20160601-23:40:48.616(0)? --------------------------------
I20160601-23:40:48.616(0)? 
I20160601-23:40:51.475(0)? 
I20160601-23:40:51.476(0)? 
I20160601-23:40:51.476(0)?   0 passing (1ms)
I20160601-23:40:51.477(0)? 
I20160601-23:40:51.808(0)? All client and server tests finished!
I20160601-23:40:51.808(0)? 
I20160601-23:40:51.812(0)? --------------------------------
I20160601-23:40:51.813(0)? SERVER FAILURES: 0
I20160601-23:40:51.814(0)? CLIENT FAILURES: 0
I20160601-23:40:51.824(0)? --------------------------------
W20160601-23:40:51.825(0)? (STDERR) 
W20160601-23:40:51.826(0)? (STDERR) /opt/tools/jenkins/workspace/Test-Job-Mocha/.tmp/meteor-test-run1uxurwr/.meteor/local/build/programs/server/packages/meteor.js:1060
W20160601-23:40:51.826(0)? (STDERR)     throw new Error("Meteor code must always run within a Fiber. " +
W20160601-23:40:51.826(0)? (STDERR)           ^
W20160601-23:40:51.837(0)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20160601-23:40:51.837(0)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
W20160601-23:40:51.838(0)? (STDERR)     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
W20160601-23:40:51.838(0)? (STDERR)     at Object.Meteor.isRestricted (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:137:1)
W20160601-23:40:51.839(0)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:268:1)
W20160601-23:40:51.840(0)? (STDERR)     at Object.UserPresence.removeConnectionsByInstanceId (packages/konecty_user-presence/packages/konecty_user-presence.js:88:1)
W20160601-23:40:51.840(0)? (STDERR)     at process.<anonymous> (packages/konecty_user-presence/packages/konecty_user-presence.js:223:1)
W20160601-23:40:51.841(0)? (STDERR)     at process.emit (events.js:117:20)
W20160601-23:40:51.841(0)? (STDERR)     at process.exit (node.js:750:17)
W20160601-23:40:51.842(0)? (STDERR)     at exitIfDone (packages/dispatch:mocha-phantomjs/server.js:60:17)
W20160601-23:40:51.842(0)? (STDERR)     at ChildProcess.done (packages/dispatch:mocha-phantomjs/server.js:89:7)
 ```

**Comment by aldeed** [comment]
Can't help much without a reproduction app. All server tests should be running within a fiber unless you have some conflicting Meteor or NPM Mocha packages screwing things up.

**Comment by allenlau** [comment]
Sent you a PR#18 to help address this issue.

**Comment by aldeed** [comment]
Thanks @allenlau, I merged and released as 0.1.3. Does that close this issue?

**Comment by allenlau** [comment]
@aldeed I think there might be an issue with my PR.  Now process will exit with status 130(SIGINT) without the fiber error caused by conflicting Meteor package.   It's better than before since we can check for a predictable status code.

I wonder if the code should be like this instead.
    if (!process.env.TEST_WATCH) {
      if (clientFailures + serverFailures > 0) {
        process.exit(2); // exit with non-zero status if there were failures
      } else {
        // Send meteor process the SIGINT status to shutdown
        // Exits with predictable status code of 130.
        process.kill(process.pid, 'SIGINT');
      }
    }

**Comment by aldeed** [comment]
@allenlau, I published 0.1.4 with that change

**Comment by aldeed** [comment]
@allenlau I forgot that most CI require exit code 0 to consider tests passing. It looks like Meteor should be running cleanup code on any exit code, though: https://github.com/meteor/meteor/blob/devel/tools/tool-env/cleanup.js#L29-L35

If you can explain how to reproduce your issue or post a link to an example repo, then maybe I can figure out another solution to this issue.

**Comment by allenlau** [comment]
@aldeed, I found the root of the issue, it is caused by the konecty:user-presence package running a process.on('exit') handler that is causing an error.  I filed an issue there to try to resolve this. 
Meanwhile, I wonder if it makes sense for this project to keep the previous behavior you have with process.exit(0) and then add an option like SHUTDOWN_NO_WAIT to exit with SIGINT to allow end users to workaround problematic packages with exit handler issues.    Otherwise, I think you can revert back to 0.1.2 behavior.   Thanks for all your help.

Something like this for SHUTDOWN_NO_WAIT
if (!process.env.TEST_WATCH) {
    if (clientFailures + serverFailures > 0) {
        process.exit(2); // exit with non-zero status if there were failures
    } else {
      if (!process.env.SHUTDOWN_NO_WAIT) {
         process.exit(0); 
      } else {
         // Send meteor process the SIGINT status to shutdown
         // Exits with predictable status code of 130
         // to deal with packages with problematic exit handlers.
         process.kill(process.pid, 'SIGINT');
     }
  }
}

**Comment by erabonza** [comment]
No longer reproducible with the changes on the konecty:user-presence package.
