### ISSUE TITLE
"Graceful exit" (v0.1.3) causes package-tests to always exit with code 130

### ISSUE THREAD

**Issue by mhwheeler** [DispatchMe/meteor-mocha-phantomjs#20]
Starting yesterday all of our package tests have started exiting 130 even with all tests passing.

Seems directly related to https://github.com/DispatchMe/meteor-mocha-phantomjs/commit/3c98251a5851141fefefa48b49f7397fac5df2ba

Is there a way to specify the driver-package version as 0.1.2? Putting it in package.js, adding it to app/.meteor/packages and running in app context and --driver-package dispatch:mocha-phantomjs@0.1.2 all seem to not work (the first two silently, the later explicitly fails)

**Comment by dard12** [comment]
Having the same problem and code 130 is failing our CircleCi tests.

You can freeze the version at `0.1.2` with `meteor add dispatch:mocha-phantomjs@=0.1.2`.

**Comment by mhwheeler** [comment]
thanks @dard12. I had tried to lock versions but was doing it wrong. I'm running as a single package test alone in its own directory. In that case the correct method is to explicitly include the package in `package.js` and include it locked like this `useAll(api, ['dispatch:mocha-phantomjs@=0.1.2']);`

**Comment by aldeed** [comment]
@mhwheeler @dard12 Sorry for the issue. Can you see if 0.1.4 fixes this for you?

**Comment by Ben305** [comment]
I'm seeing exit code 130 now with `meteor test` and 0.1.4, which also causes CI builds to fail. No problem with 0.1.2.

**Comment by aldeed** [comment]
I reverted back to the old exit codes in 0.1.5. We will figure out another solution to the problem this was attempting to solve.
