### ISSUE TITLE
Potentially Incompatible change required to top-level dependency

### ISSUE THREAD

**Issue by mofodox** [DispatchMe/meteor-mocha-phantomjs#21]
Hi,

I'm having this error saying [incompatible change required to top-level dependency](http://i.imgur.com/deWAceN.png?1). Here's my current version of meteor: Meteor 1.3.3.1.

Thank you!

**Comment by aldeed** [comment]
For now you should change your practicalmeteor:mocha package version to 2.4.5_2 to work with this package. There will be a new version of this soon with better `practicalmeteor:mocha` compatibility.

**Comment by mofodox** [comment]
@aldeed Thank you! 😄
