### ISSUE TITLE
Before Each hook always fails

### ISSUE THREAD

**Issue by firrae** [DispatchMe/meteor-mocha-phantomjs#24]
Hello,

So we've been experiencing an issue whenever we use a beforeEach hook in our Mocha tests. `undefined is not an object (evaluating 'fn.call')` is always returned when we attempt to use it. Running the Practicalmeteor web reporter it all works fine, so I'm curious if this is a known issue or how I could help in solving this issue as it is a blocking issue on our CI server tests (we prefer not using spacejam if at all possible).

Thanks,

Steve

**Comment by aldeed** [comment]
Closing old issues. This sounds like some app-specific error.
