### ISSUE TITLE
Watch mode doesn't rerun tests on changes to client.

### ISSUE THREAD

**Issue by drewmoore** [DispatchMe/meteor-mocha-phantomjs#29]
When running tests with the script: 
`TEST_WATCH=1 meteor test --driver-package dispatch:mocha-phantomjs`

When I update client tests, the tests don't run again automatically as they do when changing server test code. Updating client-side app code does rerun the tests, however.

**Comment by mwarren2** [comment]
I can confirm this.
However I find that I have to mess with some server code to get a restart, changing client code doesn't hack it.

**Comment by drewmoore** [comment]
It seems to be related to whether or not the file in question is under a directory named `client/`. My test file is under such a directory and doesn't cause test restarts. The client-facing files being tested are not under a `client/` directory and do cause tests to restart.

**Comment by mwarren2** [comment]
You may well be right.
I have a **/lib** folder under my **imports/** folder, and I can fiddle with files there and get a restart. 
But anything in a **client/** folder won't trigger a restart.

**Comment by elenadimitrova** [comment]
I can confirm this as well.

Anything under `/client` doesn't trigger test rerun
Anything under `/lib` and `/server` does

**Comment by aldeed** [comment]
This should be filed as an issue on the Meteor repo if it hasn't. Nothing can be done in a driver package to fix this.
