### ISSUE TITLE
Server tests don't actually run

### ISSUE THREAD

**Issue by tmeasday** [DispatchMe/meteor-mocha-phantomjs#3]
Try adding `assert.true(false)` in a server test on todos...

**Comment by aldeed** [comment]
It appears that having `practicalmeteor:mocha@2.1.1-rc.1` in the package list is causing it to not register any of the tests. There is a watch mode with the latest version (https://github.com/DispatchMe/meteor-mocha-phantomjs#run-app-unit-tests-in-watch-mode) so if you only have practicalmeteor:mocha included for the watch mode tests, then problem solved. :)

**Comment by aldeed** [comment]
@tmeasday, also I published another pkg now, [dispatch:mocha-browser](https://github.com/DispatchMe/meteor-mocha-browser), which runs in watch mode and reports client tests in a browser. Unlike the velocity reporters and such, server tests are still reported by mocha reporters in the server console.

**Comment by tmeasday** [comment]
@aldeed interesting.

I'm interested though. How come when using your two packages, which both `Npm.depend` on Mocha (and thus we end up with two versions of Mocha) does this issue not occur?

**Comment by aldeed** [comment]
That's a good question, maybe it actually is an issue with adding both of mine, too, but we're getting lucky regarding load order? For client tests, there might be logic in the file preventing it from loading twice, but the server tests I would think might be susceptible to ending up in the wrong instance of mocha when two packages are added.

I guess I might have to make all my mocha pkgs depend on a single pkg that sets up the server instance one time and exports it.

**Comment by tmeasday** [comment]
It would be nice if all mocha drivers depended on a single mocha package both on the client and server ;)
