### ISSUE TITLE
Invalid arguments when running client test?

### ISSUE THREAD

**Issue by FinalDes** [DispatchMe/meteor-mocha-phantomjs#33]
select: Invalid argument

**Comment by aldeed** [comment]
Try with dispatch:mocha-phantomjs@0.1.9, which uses latest phantomjs. Seems to have fixed this for me in another app, but it's possible that something else I did fixed it.

**Comment by timbrandin** [comment]
This does still not work.

**Comment by FinalDes** [comment]
@timbrandin quick fix at #35

**Comment by timbrandin** [comment]
@FinalDes awesome, will try that!

**Comment by hkalex** [comment]
No, 0.1.9 is still not working

**Comment by ninjaPixel** [comment]
@aldeed is there a MDG issue that we can vote on for this?
Thanks!

**Comment by keyscores** [comment]
+1 I"m on the latest version. I have no client tests, yet I get "select: Invalid argument" printed 100 times. Any input?

**Comment by keyscores** [comment]
See fix: https://github.com/meteor/meteor/issues/8225.
Updating to `meteor update --release 1.4.3-rc.3`  seems to fix this. Also in https://github.com/meteor/todos/issues/198

**Comment by keyscores** [comment]
@aldeed  @hwillson Digging deeper,  upgrading to 0.1.9 brings the error back. 

To be clear the fix worked for the meteor/todos app, which was at meteor-mocha-phantomjs@=0.1.7  and dispatch:phantomjs-tests@=0.0.5 when I tested.

**Comment by aldeed** [comment]
This is most likely a phantomjs or app issue, and the best solution is to stop using phantomjs. To that end, there is an updated [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha) package that supports additional browsers. See full discussion here: https://forums.meteor.com/t/is-anyone-testing-their-meteor-apps/34027/17
