### ISSUE TITLE
Feature: have an ENV variable to select client or server

### ISSUE THREAD

**Issue by keyscores** [DispatchMe/meteor-mocha-phantomjs#38]
Considering #33 , it would be nice to selectively disable the client tests (or server depending on your workflow).

**Comment by aldeed** [comment]
You can run server-only by adding `dispatch:mocha` in addition to this package and have two different NPM scripts. Then run whichever one you want.

Running client-only isn't currently possible, so we could add an option for that

**Comment by aldeed** [comment]
Moved to https://github.com/DispatchMe/meteor-mocha/issues/5 since that package will now replace this one
