### ISSUE TITLE
Why are my standard server-tests killed when adding this?

### ISSUE THREAD

**Issue by thebarty** [DispatchMe/meteor-mocha-phantomjs#4]
Hi guys,

I noticed that when adding this to my app via ``meteor add dispatch:mocha-phantomjs`` running a standard ``meteor test --driver-package practicalmeteor:mocha --port 3100;`` STOPS showing my server-tests - WITHOUT ANY ERRORS/WARNINGS in the console. When removing this package they show up again.

Any ideas whats going on here?

**Comment by aldeed** [comment]
practicalmeteor:mocha conflicts with this pkg. You might try using https://github.com/DispatchMe/meteor-mocha-browser instead.

**Comment by gergely-ujvari** [comment]
Is there any hope that this conflict will be solved anytime in the future?
This package and practicalmeteor:mocha are the two recommended/mentioned packages on the official meteor testing guide. It'd be nice if I didn't have to choose between them.

**Comment by aldeed** [comment]
It is something the practicalmeteor package needs to resolve. See https://github.com/practicalmeteor/meteor-mocha/issues/23#issuecomment-211138435
