### ISSUE TITLE
SERVER_TEST_REPORTER and CLIENT_TEST_REPORTER have no effect

### ISSUE THREAD

**Issue by vangorra** [DispatchMe/meteor-mocha-phantomjs#5]
Using the examples from the README, providing env variables for SERVER_TEST_REPORTER and CLIENT_TEST_REPORTER does not make any difference. The default test output is always shown.

Using the mocha docs (https://mochajs.org/#reporters). Tried, 'dot', 'tap', 'progress', 'nyan'. All still show the default output as if no env variables were provided.

**Comment by aldeed** [comment]
`SERVER_TEST_REPORTER` should be fixed after you `meteor update dispatch:mocha-phantomjs`. I removed ability to set client test reporter for now. Can likely add back eventually.

**Comment by vangorra** [comment]
Confirmed setting SERVER_TEST_REPORTER='tap' works.

What is preventing CLIENT_TEST_REPORTER from working?

**Comment by aldeed** [comment]
I just need to figure out the best way to transfer an env variable to client code. Server method would work, but I want to see if maybe I can just set it into `Meteor.settings.public`. Will accept a PR if someone has time to figure it out.
