### ISSUE TITLE
Error: Object has no method execfile

### ISSUE THREAD

**Issue by joshfttb** [DispatchMe/meteor-mocha-phantomjs#7]
See attached files
<img width="893" alt="screen shot 2016-04-15 at 20 15 14" src="https://cloud.githubusercontent.com/assets/2595454/14577828/7090f644-0347-11e6-91cb-6790b7c8a3aa.png">
<img width="910" alt="screen shot 2016-04-15 at 20 19 32" src="https://cloud.githubusercontent.com/assets/2595454/14577829/7091bce6-0347-11e6-989f-303ddb4eda3c.png">

**Comment by joshfttb** [comment]
This happens on my ci server as well as my local machine.

**Comment by joshfttb** [comment]
Tried to run --release 1.3.2 to see what it did to this issue, and I actually lose the first error and get a different one. Not sure if that helps
<img width="1210" alt="screen shot 2016-04-16 at 11 59 19" src="https://cloud.githubusercontent.com/assets/2595454/14582137/b971b776-03ca-11e6-99b8-b87ccdbba3ca.png">

**Comment by joshfttb** [comment]
FYI, this issue seems to not happen on 1.3.1 with practicalmeteor:mocha removed. There seems to be some conflict.

**Comment by aldeed** [comment]
Yes, this package is not compatible with practicalmeteor:mocha. Can't have both added to your app or package.

**Comment by aldeed** [comment]
Closing with reference to https://github.com/practicalmeteor/meteor-mocha/issues/23 for potential resolution
